name = "news-collector"
main = "src/collector.ts"
compatibility_date = "2024-01-29"

workers_dev = false
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "ARTICLES", id = "3033ae3d1aad4c99a7eec82d4a3077b5" }
]

[vars]
FEED_URLS = [
    "https://cdn.feedcontrol.net/7487/11169-gt9l6GJXjK2be.json",
    "https://cdn.feedcontrol.net/7487/11168-xnKjjg7sUDPAD.json",
    "https://cdn.feedcontrol.net/7487/11167-tbTnM2SiBLArG.json",
    "https://cdn.feedcontrol.net/7487/11170-a3wbiATi2URpg.json",
    "https://cdn.feedcontrol.net/7487/11171-HXUb0hJIOblbg.json",
    "https://cdn.feedcontrol.net/7487/11172-6BzD2eGRpeTlT.json",
]

[triggers]
crons = [ "*/30 * * * *" ]

[dev]
port = 8788
