name = "news-app"
main = "src/app.ts"
compatibility_date = "2024-01-29"

workers_dev = true
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "ARTICLES", id = "3033ae3d1aad4c99a7eec82d4a3077b5" }
]

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "articles-index"

[ai]
binding = "AI"

[site]
bucket = "./public"
