name = "news-collector"
main = "src/collector.ts"
compatibility_date = "2024-01-29"

workers_dev = false
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "ARTICLES", id = "3033ae3d1aad4c99a7eec82d4a3077b5" }
]

[vars]
FEED_URL = "https://cdn.feedcontrol.net/7487/11169-gt9l6GJXjK2be.json"

[triggers]
crons = [ "*/30 * * * *" ]

[dev]
port = 8788
